/**
 * @file types.ts
 * @summary Defines the core data structures and types used throughout the Shared Meal Manager application.
 */

/**
 * Represents a user authenticated via Firebase.
 */
export interface User {
  /** The unique identifier for the user, provided by Firebase Auth. */
  uid: string;
  /** The user's email address. */
  email: string | null;
}

/**
 * Represents a member in the shared meal plan.
 */
export interface Member {
  /** The unique identifier for the member, generated by Firestore. */
  id: string;
  /** The name of the member. */
  name: string;
}

/**
 * Represents a single grocery purchase.
 */
export interface GroceryItem {
  /** The unique identifier for the grocery item, generated by Firestore. */
  id: string;
  /** The date of purchase in 'YYYY-MM-DD' format. */
  date: string;
  /** A description of the item(s) purchased. */
  item: string;
  /** The cost of the item. */
  amount: number;
}

/**
 * Represents a financial deposit made by a member.
 */
export interface Deposit {
  /** The unique identifier for the deposit, generated by Firestore. */
  id: string;
  /** The date of the deposit in 'YYYY-MM-DD' format. */
  date: string;
  /** The ID of the member who made the deposit. */
  memberId: string;
  /** The amount of money deposited. */
  amount: number;
}
